### ISSUE TITLE
Content not centered after animation.

### ISSUE THREAD

**Issue by shidel-dev** [auchenberg/chrome-devtools-app#15]
![screen shot 2014-12-31 at 9 59 33 am](https://cloud.githubusercontent.com/assets/5149882/5588675/d3005370-90d3-11e4-953c-3f6c7875a000.png)

After clicking a debugging target the page animates and ends up not centered.

This occurs consistently, and can only be fixed by resizing the page.

**Comment by auchenberg** [comment]
Which OS version are on? I can't reproduce this.

**Comment by auchenberg** [comment]
Closing for now. Can't reproduce.
