### ISSUE TITLE
Missing some devtools files

### ISSUE THREAD

**Issue by shidel-dev** [auchenberg/chrome-devtools-app#16]
![screen shot 2014-12-31 at 10 09 08 am](https://cloud.githubusercontent.com/assets/5149882/5588733/24e09a1e-90d5-11e4-8817-099cf6064ba7.png)

Are these intently left out?

**Comment by auchenberg** [comment]
Fixed in https://github.com/auchenberg/chrome-devtools-app/commit/64dec737ffdcef0e115dd084c125e6232ea2085c.
