### ISSUE TITLE
Unique app icon

### ISSUE THREAD

**Issue by auchenberg** [auchenberg/chrome-devtools-app#2]
The currently used icon is https://www.iconfinder.com/icons/317753/browser_chrome_internet_web_web_browser_icon#size=512

We should have a proper icon for DevTools.

**Comment by rnewton** [comment]
Really rough, but what about something like this? 

![chrome-dev-tools-concept](https://cloud.githubusercontent.com/assets/445976/7472886/e9719950-f304-11e4-8649-750ae642c9fc.png)

**Comment by auchenberg** [comment]
Honestly I'd prefer the existing logo:
 ![](https://raw.githubusercontent.com/auchenberg/chrome-devtools-app/master/app/icon/logo.png), as it resembles Chrome in "appy" context.

**Comment by jasonLaster** [comment]
I'd like to see a magnifying glass become more prominent :mag: :mag_right:

**Comment by auchenberg** [comment]
Resolved by using official Chrome DevTools logo.
