### ISSUE TITLE
Uncaught node.js Error

### ISSUE THREAD

**Issue by masnun** [auchenberg/chrome-devtools-app#20]
I downloaded the .app file for OS X and when I double clicked on the app file, I get this -- http://screencast.com/t/Q56HXqcEhf3

**Comment by shrop** [comment]
I received the same error. Be glad to try again with some guidance.

**Comment by auchenberg** [comment]
Looks like the zip contained a broken build of the app. I pushed a new build, and ZIP.

Let me know how it works for you.

**Comment by masnun** [comment]
It worked, thanks.
