### ISSUE TITLE
Issue installing via npm

### ISSUE THREAD

**Issue by capnross** [auchenberg/chrome-devtools-app#23]
I have node installed, here are version object details:

{ http_parser: '1.0',
  node: '0.10.13',
  v8: '3.14.5.9',
  ares: '1.9.0-DEV',
  uv: '0.10.12',
  zlib: '1.2.3',
  modules: '11',
  openssl: '1.0.1e',
  npm: '1.3.2' }

And when I run the npm install nodewebkit, it runs smoothly until near the end. Screenshot below from iTerm:

![image](https://cloud.githubusercontent.com/assets/777206/5641772/82e7f93e-9636-11e4-8e5a-5c2d549acda6.png)

Thanks for working on this, it's a great concept.

Best,

Tony

**Comment by auchenberg** [comment]
It seems like you are running node ``0.10.13``. I'm running ``0.10.33`` and have no issues.

Can you try upgrading?

**Comment by capnross** [comment]
Thanks. That worked and the app now runs. However, like another of your 
comments, although when running an instance of Chrome in remote debugging 
mode, I can see the page in the pages window on the app, clicking on it 
opens an empty window in the app.

From:  Kenneth Auchenberg <notifications@github.com>
Reply-To:  auchenberg/chrome-devtools-app 
<reply+000bdbf63d2ce2a823c15fc70fbde754924bb8cc1e4c941792cf0000000110c6c050
92a169ce0331e823@reply.github.com>
Date:  Thursday, 8 January 2015 22:01
To:  auchenberg/chrome-devtools-app 
<chrome-devtools-app@noreply.github.com>
Cc:  Tony Ross <capn.ross@gmail.com>
Subject:  Re: [chrome-devtools-app] Issue installing via npm (#23)


It seems like you are running node 0.10.13. I'm running 0.10.33 and have 
no issues.

Can you try upgrading?

**Comment by auchenberg** [comment]
Can I get you to toggle the DevTools, and give me the output from the console?

![fullscreen](https://cloud.githubusercontent.com/assets/173559/5823155/b8036fbe-a0da-11e4-98ad-5b692d000d05.png)

**Comment by auchenberg** [comment]
You there?

**Comment by capnross** [comment]
Hello!

**Comment by auchenberg** [comment]
Closing has details hasn't been provided.
