### ISSUE TITLE
Copying requests as cURL does not work

### ISSUE THREAD

**Issue by gingermusketeer** [auchenberg/chrome-devtools-app#30]
Apparently the clipboard is not enabled in hosted mode.

![screen shot 2015-02-13 at 7 51 17 pm](https://cloud.githubusercontent.com/assets/1177034/6184757/fd062f42-b3b9-11e4-8a17-60d9d34ce7f0.png)

Any idea why this is?

**Comment by auchenberg** [comment]
Looks like nw.js had the same problem, https://github.com/nwjs/nw.js/issues/2660

**Comment by gingermusketeer** [comment]
I was not able to see anything in the PR (nwjs/nw.js#2917) to fix the above issue that we could reuse here.

I was able to figure out that the InspectorFrontendHost we are currently using is a stub. It has the same api but either does nothing or it throws errors. So i have created a PR to add a nwjs compatible frontend host. See #35
