### ISSUE TITLE
Usage in combination with bugger

### ISSUE THREAD

**Issue by jkrems** [auchenberg/chrome-devtools-app#44]
FYI, I just verified that it works with `bugger`:

1. Start node app with `bugger --port 9222 my-node-script.js`
2. Open Chrome DevTools App
3. ...
4. Profit!

**Comment by auchenberg** [comment]
Yay :)

How's `bugger` different from node-inspector?

**Comment by jkrems** [comment]
From a user perspective:

* Requires starting the app via `bugger`, can't connect to a "normal" node app.
* Some additional features like support for workers via `child_process#fork`.
* Not backed by a company like StrongLoop but just one person's hobby project so rather unreliable.

From a technical perspective:

* Doesn't use the V8 debug API but instead exposes the devtools protocol directly from the target process (using a separate thread for the websocket IO so it still works while the VM is paused).
* Uses the native devtools UI that ship with Chrome, not a patched version.
* Exposes the JSON API required by `chrome://inspect`.

**Comment by auchenberg** [comment]
Aha, didn't know!
