### ISSUE TITLE
Where are the dev tools source?

### ISSUE THREAD

**Issue by jcampbell05** [auchenberg/chrome-devtools-app#46]
Just wondering where did you find the developer tool source code ?

**Comment by vanjacosic** [comment]
@auchenberg mentions in [this blogpost](https://kenneth.io/blog/2014/12/28/taking-chrome-devtools-outside-the-browser/) that he found the source here: 
https://chromium.googlesource.com/chromium/blink/+/master/Source/devtools/
:)

**Comment by jcampbell05** [comment]
Thank you very much ! :)
