### ISSUE TITLE
can't get targets to show up

### ISSUE THREAD

**Issue by matthewdias** [auchenberg/chrome-devtools-app#47]
I'm a little confused about how to get targets to show up. started chrome with `--remote-debugging-port=9222`, and navigated to a webpage. No targets found. Am i doing something wrong?

**Comment by auchenberg** [comment]
It should be working. Can you try going to `http://localhost:9222/json` in a browser while Chrome is running?

**Comment by matthewdias** [comment]
nevermind I had another chrome process that was blocking it. All good.
