### ISSUE TITLE
Discontinued project?

### ISSUE THREAD

**Issue by outaTiME** [auchenberg/chrome-devtools-app#48]
Hi pal, no more updates from 2015 ... you leave this project ??

thks !!!

**Comment by auchenberg** [comment]
Yup, not really maintained. Wanna contribute @outaTiME ?

**Comment by varp** [comment]
Why is the project discontinued?

**Comment by auchenberg** [comment]
@varp Simply because I don't have the time to evolve this project.

**Comment by varp** [comment]
@auchenberg Thx for reply

**Comment by morenoh149** [comment]
Should close the issue as non-issue.
