### ISSUE TITLE
Missing right-click context menu in Elements tab

### ISSUE THREAD

**Issue by pwlin** [auchenberg/chrome-devtools-app#6]
Thanks for this useful app! I have a minor issue: 
on the Elements tab, right clicking on an element does not bring up right-click context menu. 
Strangely enough, right-click context menu works perfect on all other tabs. Is this something related to Node-Webkit?

**Comment by serious-angel** [comment]
Just in case, I am sorry for raising the 2014 topic.
Have you tried changing the DevTools zoom level (e.g. increase to 100% or more)?

> \- It seems as if the context menu is inaccessible below certain font sizes.
> \- Indeed, the context menu depends on the DevTools zoom level, and its high enough value enables the menu.

Source: <https://stackoverflow.com/a/71574207/5113030>
